# Generated by Django 4.1.5 on 2023-04-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="yellow_card",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
