# Generated by Django 4.1.5 on 2023-04-05 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_temporalnickname_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="temporalnickname",
            name="user",
        ),
    ]
