# Generated by Django 4.1.5 on 2023-04-05 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_temporalnickname_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="temporalnickname",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="temp",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
