# Generated by Django 4.1.5 on 2023-04-18 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="users_user_nicknam_f432f0_idx",
        ),
    ]
