# Generated by Django 4.1.5 on 2023-04-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_user_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("today_user", models.PositiveIntegerField(default=0)),
                ("realtime_user", models.PositiveIntegerField(default=0)),
                ("current_user", models.PositiveIntegerField(default=0)),
                ("total_user", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
