# Generated by Django 4.1.5 on 2023-04-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_siteinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteinfo",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="siteinfo",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
