# Generated by Django 4.1.5 on 2023-04-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_preferenceinfo_siteinfo_today_drop_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="preferenceinfo",
            name="gender",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
