# Generated by Django 4.1.5 on 2023-04-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_preferenceinfo_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteinfo",
            name="today_success_message",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
