# Generated by Django 4.1.5 on 2023-04-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="title",
            field=models.CharField(
                choices=[("E", "오류"), ("U", "불편사항"), ("R", "건의사항"), ("C", "칭찬")],
                max_length=10,
            ),
        ),
    ]
