# Generated by Django 4.1.5 on 2023-04-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flavors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flavor",
            name="img",
            field=models.CharField(default="", max_length=255),
        ),
    ]
