# Generated by Django 4.1.5 on 2023-04-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flavors", "0002_flavor_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flavor",
            name="img",
            field=models.CharField(max_length=255),
        ),
    ]
