# Generated by Django 4.1.5 on 2023-04-10 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("msgs", "0003_alter_message_is_anonymous"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="receiver",
            field=models.ForeignKey(
                default=11,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="receiver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                default=11,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="sender",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
