# Generated by Django 4.1.5 on 2023-04-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0005_spam"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="sender_canceled",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
